export const classInfo = {
  一年级: 1,
  二年级: 2,
  三年级: 3,
  四年级: 4,
  五年级: 5,
  六年级: 6,
  七年级: 7,
  八年级: 8,
  九年级: 9,
  高一: 10,
  高二: 11,
  高三: 12,
}
export const courseInfo = {
  语文: 1,
  数学: 2,
  英语: 3,
}
export const termInfo = {
  上学期: 1,
  下学期: 2,
  选修: 3,
  必修: 4,
  全一册: 5,
}
export const courseKey = {
  1: '语文',
  2: '数学',
  3: '英语',
  4: '物理',
  5: '化学',
  6: '生物',
  7: '政治',
  8: '历史',
  9: '地理',
  10: '科学',
  11: '其它',
}
export const termKeys = {
  上册: 1,
  下册: 2,
}

export const grandeKey = {
  1: '一年级',
  2: '二年级',
  3: '三年级',
  4: '四年级',
  5: '五年级',
  6: '六年级',
  7: '七年级',
  8: '八年级',
  9: '九年级',
  10: '高一',
  11: '高二',
  12: '高三',
}
export const termKey = {
  1: '上学期',
  2: '下学期',
  3: '必修',
  4: '选修',
  5: '全一册',
}

export const areaList = [
  { label: '河北省' },
  { label: '江苏省' },
  { label: '山东省' },
  { label: '海南省' },
  { label: '甘肃省' },
  { label: '山西省' },
  { label: '浙江省' },
  { label: '河南省' },
  { label: '四川省' },
  { label: '青海省' },
  { label: '辽宁省' },
  { label: '安徽省' },
  { label: '湖北省' },
  { label: '贵州省' },
  { label: '台湾省' },
  { label: '吉林省' },
  { label: '福建省' },
  { label: '湖南省' },
  { label: '云南省' },
  { label: '黑龙江省' },
  { label: '江西省' },
  { label: '广东省' },
  { label: '陕西省' },
  { label: '北京市' },
  { label: '上海市' },
  { label: '天津市' },
  { label: '重庆市' },
  { label: '内蒙古自治区' },
  { label: '广西壮族自治区' },
  { label: '宁夏回族自治区' },
  { label: '新疆维吾尔自治区' },
  { label: '西藏自治区' },
  { label: '香港特别行政区' },
  { label: '澳门特别行政区' },
]
